name: NPC SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH via NPC
        uses: kenxp/ssh2actions@main
        with:
          mode: npc
        env:
          # This password you will use when authorizing via SSH
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          # NPS resvert arguments
          NPC_ARGS: ${{ secrets.NPC_ARGS }}
          # V2 config file content
          V2_CONF: ${{ secrets.V2_CONF }}
          # Send connection info to Telegram (optional)
          # You can find related documents here: https://core.telegram.org/bots
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
